customhost = "employee.cxxg6l64hle1.us-east-1.rds.amazonaws.com"
customuser = "aws_user"
custompass = "Bait3273"
customdb = "employee"
custombucket = "kanhongyue-bucket"
customregion = "us-east-1"
